site_name: Mkdocs Template

site_url: https://giswqs.github.io/mkdocs-template

repo_url: https://github.com/giswqs/mkdocs-template

theme:
  palette:
    scheme: preference
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    # - navigation.expand
    # - navigation.tabs
    - search.highlight
  custom_dir: "docs/overrides"

plugins:
  - search
  - mkdocstrings
  - git-revision-date
  - mkdocs-jupyter:
      include_source: True
      execute: False

markdown_extensions:
  - attr_list
  - toc:
      permalink: true

# google_analytics:
#   - UA-XXXXXXXX-X
#   - auto

nav:
  - Home: index.md
  - Chapter 1:
    - ch01/SOBEK模式介紹.md
      # - chapter_01/intro.ipynb
      # - chapter_01/basemaps.ipynb
  - Chapter 2:
    - ch02/模式介面介紹.md
      # - chapter_02/colorbar.ipynb
      # - chapter_02/heatmap.ipynb
  - Chapter 3:
    - ch03/專案資料夾結構.md
  - Blog: https://blog.gishub.org
  - YouTube Channel: https://www.youtube.com/c/QiushengWu
  - Report Issues: https://github.com/giswqs/mkdocs-template/issues
